# aetheria_core：純 C++ 玩法核心（不得依賴 godot-cpp）。

add_library(aetheria_core STATIC
    core/api/version.cpp
    core/rules/ruleset.cpp
    core/rules/ruleset_load_defs.cpp
    core/rules/ruleset_load_site.cpp
    core/rules/ruleset_load_site_city.cpp
    core/rules/ruleset_load_site_build.cpp
    core/rules/ruleset_load_site_wilderness.cpp
    core/rules/ruleset_load_biomes.cpp
    core/rules/ruleset_load_civilization.cpp
    core/rules/ruleset_load_factions.cpp
    core/rules/ruleset_load_history.cpp
    core/rules/ruleset_load_history_values.cpp
    core/rules/ruleset_load_history_references.cpp
    core/rules/ruleset_load_crossings.cpp
    core/rules/ruleset_load_world_graph.cpp
    core/serialize/normalized_state_hash.cpp
    core/site/site_event_escalation.cpp
    core/site/site_build_loop.cpp
    core/site/site_build_economy.cpp
    core/site/site_materialize.cpp
    core/site/site_population.cpp
    core/site/site_zoning.cpp
    core/site/site_buildings.cpp
    core/site/site_building_placement.cpp
    core/site/site_fortifications.cpp
    core/site/site_landmarks.cpp
    core/site/site_damage.cpp
    core/site/site_projection.cpp
    core/site/site_skeleton_common.cpp
    core/site/site_skeleton_center.cpp
    core/site/site_skeleton_terrain.cpp
    core/site/site_skeleton_roads.cpp
    core/site/site_skeleton_blocks.cpp
    core/site/site_wilderness.cpp
    core/site/site_wilderness_entities.cpp
    core/site/site_wilderness_boundary.cpp
    core/site/site_wilderness_boundary_seed.cpp
    core/site/site_wilderness_terrain.cpp
    core/site/site_wilderness_pathfinding.cpp
    core/site/site_wilderness_paths.cpp
    core/site/site_wilderness_content.cpp
    core/site/site_reduction.cpp
    core/time/tick.cpp
    core/serialize/zone_encode.cpp
    core/serialize/zone_decode.cpp
    core/zone/file_zone_store.cpp
    core/zone/save_manifest_io.cpp
    core/zone/zone_manager.cpp
    core/zone/zone_store.cpp
    core/world/region_tiles.cpp
    core/world/region_simulation.cpp
    core/world/region_step_cost.cpp
    core/world/region_path.cpp
    core/world/region_turn.cpp
    core/worldgen/civ_tiles.cpp
    core/worldgen/city_scoring.cpp
    core/worldgen/settlement_scoring.cpp
    core/worldgen/city_selection.cpp
    core/worldgen/city_sites.cpp
    core/worldgen/feature_placement.cpp
    core/worldgen/history_roads.cpp
    core/worldgen/history_layer.cpp
    core/worldgen/influence_spread.cpp
    core/worldgen/influence_claim.cpp
    core/worldgen/governance_release.cpp
    core/worldgen/capital_selection.cpp
    core/worldgen/portal_generation.cpp
    core/worldgen/portal_candidates.cpp
    core/worldgen/portal_boundary_candidates.cpp
    core/worldgen/faction_generation.cpp
    core/worldgen/road_path.cpp
    core/worldgen/road_loops.cpp
    core/worldgen/road_network.cpp
    core/worldgen/region_seed.cpp
    core/worldgen/stage_plates.cpp
    core/worldgen/stage_height.cpp
    core/worldgen/stage_erosion.cpp
    core/worldgen/stage_climate.cpp
    core/worldgen/stage_rivers.cpp
    core/worldgen/stage_biomes.cpp
    core/worldgen/stage_features.cpp
    core/worldgen/region_build.cpp
    core/worldgen/region_populate.cpp
    core/worldgen/region_stage_hash.cpp
    core/worldgen/region_result_hash.cpp
    core/worldgen/region_debug.cpp
)
target_include_directories(aetheria_core PUBLIC "${PROJECT_SOURCE_DIR}")
target_link_libraries(aetheria_core
    PUBLIC EnTT::EnTT
    PRIVATE cereal::cereal tomlplusplus::tomlplusplus zstd::libzstd_static
)
aetheria_enable_warnings(aetheria_core)
